linters:
  StringQuotes:
    enabled: false
  Shorthand:
    enabled: false
  PropertySortOrder:
    enabled: false
  IdSelector:
    enabled: false
  QualifyingElement:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    enabled: false
  NestingDepth:
    enabled: true
    max_depth: 6
    ignore_parent_selectors: false
  SelectorDepth:
    enabled: true
    max_depth: 6
  Comment:
    enabled: false
  VendorPrefix:
    enabled: false
  SelectorFormat:
    enabled: false
  NameFormat:
    enabled: false
  TrailingWhitespace:
    enabled: false
exclude: src/AppBundle/Resources/assets/scss/email-template/inline-styles.scss
