version: '3.2'

services:
    test:
        build: ./behat
        depends_on:
            - sirius-integration-api
        volumes:
            - ./behat/tests:/var/www/tests
            - ./behat/snapshots:/tmp/html
        env_file: ./behat/test.env
        environment:
          AWS_ACCESS_KEY_ID: fakeValue
          AWS_SECRET_ACCESS_KEY: fakeValue
          AWS_SESSION_TOKEN: fakeValue

    npm:
        image: node:8-alpine
        working_dir: /app
        volumes:
            - ./client/:/app
        entrypoint: npm
        environment:
            NODE_ENV: production

    composerapi:
        image: composer
        volumes:
            - ./api/:/app

    composerfront:
        image: composer
        volumes:
            - ./client/:/app

    frontend:
        env_file: ./behat/test.env

    admin:
        env_file: ./behat/test.env

    sirius-integration-api:
        image: muonsoft/openapi-mock
        ports:
            - 6060:8080
        environment:
            OPENAPI_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/ministryofjustice/opg-data/master/docs/deputy-reporting-openapi-v1.yml'
