imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

monolog:
   handlers:
       main:
           formatter: line_formatter
           
jms_serializer:
    metadata:
        cache: none
        cache: file
        debug: true           
