imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

services:
    data_collector.apiCollectorss:
        class: AppBundle\Service\ApiCollector
        arguments: ["@rest_client"]
        tags:
            - { name: data_collector, template: "AppBundle:Manage:api-collector", id: "api-collector" }
    s3_client:
        class: Aws\S3\S3Client
        arguments:
          -
            version: 'latest'
            region: 'eu-west-2'
            endpoint: 'http://fakes3:4569'
            validate: false
            credentials:
              key: 'YOUR_ACCESS_KEY_ID'
              secret: 'YOUR_SECRET_ACCESS_KEY'



#swiftmailer:
#    delivery_address: me@example.com

monolog:
   handlers:
       main:
           formatter: line_formatter

jms_serializer:
    metadata:
        cache: none
        cache: file
        debug: true 