imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

services:
    data_collector.apiCollectorss:
        class: AppBundle\Service\ApiCollector
        arguments: [@restClient]
        tags:
            - { name: data_collector, template: "AppBundle:Manage:api-collector", id: "api-collector" }


#swiftmailer:
#    delivery_address: me@example.com

monolog:
   handlers:
       main:
           formatter: line_formatter
