imports:
    - { resource: config.yml }

services:
  # see arguments here http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
  s3_client:
    class: Aws\S3\S3Client
    arguments:
      -
        version: 'latest'
        region: 'eu-west-2'
        validate: true

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
