imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   digideps_unit_test
        
services:
    mailSender:
        class: AppBundle\Service\Mailer\MailSenderMock
        arguments: [ @service_container ]
    mailer.transport.smtp.default:
        class: AppBundle\Service\Mailer\Transport\FileWriter
        arguments: [ "/tmp/dd_transport_smtp_default" ]
    mailer.transport.smtp.secure:
        class: AppBundle\Service\Mailer\Transport\FileWriter
        arguments: [ "/tmp/dd_transport_smtp_secure" ]