imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        #options:
            #sslmode: require

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        
doctrine_migrations:
    table_name: migrations

            
services:
    kernel.listener.responseConverter:
        class: AppBundle\EventListener\RestInputOuputFormatter
        arguments: [ @serializer, ["json"], "%kernel.debug%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }            
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }      
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }      
    em:
        alias: doctrine.orm.entity_manager
        
fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        AppBundle\Entity\OAuth2Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode
    service:
        user_provider: userprovider
        options:
            supported_scopes: user
        
        
#jms_serializer:
#    metadata:
##        cache: none
##        cache: file
#        debug: "%kernel.debug%"