parameters:
    api_endpoints:
        find_user_by_email: user/get-by-email
        add_user: user
        list_users: user
        find_user_by_token: user/get-by-token
        list_roles: role
        get_all_court_order_type: court-order-type/all
        add_client: client/add
        find_client_by_id: client/find-by-id
        add_report: report/add
        find_report_by_id: report/find-by-id
        add_decision: decision/add
        find_decision_by_report_id: decision/find-by-report-id
        add_report_contact: report/add-contact
        get_report_contacts: report/get-contacts
        add_report_account: report/add-account
        get_report_accounts: report/get-accounts
        get_report_assets: report/get-assets
        add_report_asset: report/add-asset
