parameters:
    api_endpoints:
        find_user_by_email: user/get-by-email
        add_user: user
        list_users: user
        find_user_by_token: user/get-by-token
        list_roles: role
        get_all_court_order_type: court-order-type/all
        add_client: client/add
        find_client_by_id: client/find-by-id
        add_report: report/add
