parameters:
    api_endpoints:
        # user
        find_user_by_email: user/get-user-by-email
        find_admin_by_email: user/get-admin-by-email
        find_by_email: user/get-by-email
        add_user: user
        edit_user: user
        list_users: user
        find_user_by_token: user/get-by-token/hybrid
        find_user_by_token_deputy: user/get-by-token/deputy
        find_user_by_token_admin: user/get-by-token/admin
        list_roles: role
        find_user_by_id: user
        delete_user_by_id: user
        #client
        get_all_court_order_type: court-order-type/all
        add_client: client/upsert
        update_client: client/upsert
        find_client_by_id: client/find-by-id
        # report
        add_report: report/upsert
        clone_report: report/clone
        find_report_by_id: report/find-by-id
        add_decision: decision/upsert
        update_decision: decision/upsert
        delete_decision: decision
        find_decision_by_report_id: decision/find-by-report-id
        add_report_contact: report/upsert-contact
        update_report_contact: report/upsert-contact
        get_report_decision: decision
        get_report_contacts: report/get-contacts
        get_report_contact: report/get-contact
        add_report_account: report/add-account
        get_report_accounts: report/get-accounts
        find_account_by_id: report/find-account-by-id
        get_report_assets: report/get-assets
        delete_report_contact: report/delete-contact
        add_report_asset: report/upsert-asset
        update_report_asset: report/upsert-asset
        get_report_asset: report/get-asset
        delete_report_asset: report/delete-asset
