security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: sha512
       

    role_hierarchy:
        ROLE_LAY_DEPUTY: []
        ROLE_PROFESSIONAL_DEPUTY: []
        ROLE_LOCAL_AUTHORITY_DEPUTY: []
        ROLE_ADMIN: [ ROLE_ALLOWED_TO_SWITCH, ROLE_GUEST, ROLE_LAY_DEPUTY, ROLE_PROFESSIONAL_DEPUTY, ROLE_LOCAL_AUTHORITY_DEPUTY, ROLE_VISITOR ]

    providers:
#        in_memory:
#            memory: ~
        user_provider:
            id: userprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        elb:
            pattern: ^/manage/elb
            security: false
            
        default:
            anonymous: ~

        login:
            pattern:  ^/auth/login$
            security: false

       # secured_area:
       #     pattern:    ^/demo/secured/
       #     form_login:
       #         check_path: _security_check
       #         login_path: _demo_login
       #     logout:
       #         path:   _demo_logout
       #         target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #temp. REMOVEME
        - { path: ^/user/get-all, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: IS_AUTHENTICATED_FULLY }
        
        
