parameters:
    # set this param to a higher value than session_expire_seconds on the client
    user_provider_timeout_seconds: 3901
    
services:
    # authenticator
    authenticator.token_header:
        class: AppBundle\Service\Auth\HeaderTokenAuthenticator
        public: false
    user_provider:
        class: AppBundle\Service\Auth\UserProvider
        arguments: [ @em, @snc_redis.default, @logger, { "timeout_seconds": "%user_provider_timeout_seconds%" } ]
    authService:
        class: AppBundle\Service\Auth\AuthService
        arguments: [ @service_container ]
    
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: sha512
       
    
    providers:
        user_provider_redis:
            id: user_provider

    firewalls:
        elb:
            pattern: ^/manage/
            security: false
            methods: [GET]
        # disabled at the controller level if "behat_controller_enabled" param is equal to false
        behat:
            pattern: ^/behat/
            security: false
        login:
            pattern:  ^/auth/login$
            security: false
            methods: [POST]
        userRecreateToken:
            pattern: ^/user/recreate-token
            security: false
            methods: [PUT]
        userGetByToken:
            pattern: ^/user/get-by-token
            security: false
            methods: [GET]
        selfregister:
            pattern: ^/selfregister
            security: false
            methods: [POST]
        # keep this one last so that the previous ones bypass the catch-all pattern below
        default:
            pattern: .*
            security: true
            simple_preauth:
                authenticator: authenticator.token_header
            provider: user_provider_redis
            stateless:   true
            
#    access_control:
#        - { path: ^/audit-log, roles: [ROLE_ADMIN, IS_AUTHENTICATED_FULLY] }
#    role_hierarchy:
#        ROLE_LAY_DEPUTY: []
#        ROLE_ADMIN: [ ]

        
        
