security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_LAY_DEPUTY: [ ROLE_DEPUTY ]
        ROLE_PROFESSIONAL_DEPUTY: [ ROLE_DEPUTY ]
        ROLE_LOCAL_AUTHORITY_DEPUTY: [ ROLE_DEPUTY ]
        ROLE_ADMIN: [ ROLE_ALLOWED_TO_SWITCH, ROLE_DEPUTY ]

    providers:
        deputy:
           id: deputyprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            
        userActivate:
            pattern:  ^/user/activate
            security: false
        
        behatControllers:
            pattern:  ^/behat
            security: false
            
        manageController:
            pattern:  ^/manage/availability
            security: false

        secured_area:
            form_login:
                #check_path: /login_check
                login_path: /login
                #username_parameter: login[email]
                #password_parameter: login[password]
            logout:
                path:   /logout
                target: /
                success_handler: logout_listener
            anonymous: ~
            switch_user: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/ , roles: IS_AUTHENTICATED_FULLY }
