security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_LAY_DEPUTY: []
        ROLE_PROFESSIONAL_DEPUTY: []
        ROLE_LOCAL_AUTHORITY_DEPUTY: []
        ROLE_ADMIN: [ ROLE_ALLOWED_TO_SWITCH, ROLE_GUEST, ROLE_LAY_DEPUTY, ROLE_PROFESSIONAL_DEPUTY, ROLE_LOCAL_AUTHORITY_DEPUTY, ROLE_VISITOR ]

    providers:
        deputy:
           id: deputyprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            form_login:
                check_path: /login_check
                login_path: /login
                username_parameter: email
                password_parameter: password
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: IS_AUTHENTICATED_FULLY }
