services:
    kernel.listener.responseConverter:
        class: AppBundle\EventListener\RestInputOuputFormatter
        arguments: [ @serializer, @logger, ["json"], "json", "%kernel.debug%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }            
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }      
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }      
    em:
        alias: doctrine.orm.entity_manager  
    # default transport + swift mailer
    mailer.transport.smtp.default:
        class: Swift_SmtpTransport
        arguments: [ "%smtp_default_hostname%", "%smtp_default_port%" ]
        calls:
            - [ setEncryption, [ "tls"]]
            - [ setUsername, [ %smtp_default_user%]]
            - [ setPassword, [ %smtp_default_password%]]
    mailer.swiftMailers.default:
        class: Swift_Mailer
        arguments: [ @mailer.transport.smtp.default ]
    # secure transport + swift mailer
    mailer.transport.smtp.secure:
        class: Swift_SmtpTransport
        arguments: [ "%smtp_secure_hostname%", "%smtp_secure_port%" ]
    mailer.swiftMailers.secure:
        class: Swift_Mailer
        arguments: [ @mailer.transport.smtp.secure ]
    # mail sender accepting those the above-created swift mailer
    mailSender:
        class: AppBundle\Service\Mailer\MailSender
        arguments: [ @validator ]
        calls:
            - [ addSwiftMailer, [ "default", @mailer.swiftMailers.default] ]
            - [ addSwiftMailer, [ "secure-smtp" , @mailer.swiftMailers.secure] ]
            - [ writeToFileEmailMatching, ["%email_mock_address%", "%email_mock_path%"] ]
    mailFactory:
        class: AppBundle\Service\Mailer\MailFactory
        arguments: [ @service_container, {"ROLE_ADMIN": "admin", "ROLE_AD": "admin", "ROLE_LAY_DEPUTY": "admin"} ]
    componentsExtension:
        class: AppBundle\Twig\ComponentsExtension
        public: false
        arguments: [  @translator ]
        tags:
            - { name: twig.extension }
    user.selfRegistration:
        class: AppBundle\Service\UserRegistrationService
        arguments: [@doctrine.orm.entity_manager, @mailFactory, @mailSender]
