services:
    mailer.service:
            class: AppBundle\Mailer\MailerService
#            arguments: [@swiftmailer.transport.sendmail, @templating]
            arguments: [@mailer.transport.fileWriter]
            
    mailer.transport.fileWriter:
                class: AppBundle\Mailer\Transport\FileWriter
                arguments: [ "/tmp/dd_mail_mock" ]
    mailer.transport.sendgrid:
                class: AppBundle\Mailer\Transport\Sendgrid
    mailer.factory:
            class: AppBundle\Mailer\MailerFactory
            arguments: [ @mailer.service, @translator, @router]
                
