imports:
    - { resource: endpoints.yml }
    - { resource: twig.yml }
    
services:
    security.validator.d_user_password:
        class: AppBundle\Validator\Constraints\DUserPasswordValidator
        arguments: [ @security.context, @security.encoder_factory ]
        tags:
            - { name: validator.constraint_validator, alias: security.validator.d_user_password }
    oauth2client:
        class: AppBundle\Service\OAuth\OAuth2
        arguments: [ "%api_base_url%", %oauth2_client_id%, %oauth2_client_secret%]
    dd_session.memcached_handler:
        class: AppBundle\Service\MemcachedSessionHandler
        arguments: [ "%session_memcached_host%", "%session_memcached_port%" ]
    oauth.memcached:
        class: Memcached
        arguments:
            persistent_id: 'api_oauth2'
        calls:
            - [ addServer, [ %session_memcached_host%, %session_memcached_port%]]
    apiclient:
        class:  AppBundle\Service\ApiClient
        arguments: 
          - @service_container
          - 
              format: "json"
              base_url: "%api_base_url%"
              use_redis: "%use_redis%"
              use_memcached: "%use_memcached%"
              use_oauth2: "%oauth2_enabled%"
              endpoints: "%api_endpoints%"
              debug: "%kernel.debug%"
              collectData: "%kernel.debug%"
    deputyprovider:
        class:  AppBundle\UserProvider\DeputyProvider
        arguments: [ @service_container,%env% ]
    userService:
        class:  AppBundle\Service\UserService
        arguments: [ @apiclient, %env% ]
    util:
        class: AppBundle\Service\Util
        arguments: [@apiclient]
    formFieldsExtension:
        class: AppBundle\Twig\FormFieldsExtension
        public: false
        arguments: [ @translator ]
        tags:
            - { name: twig.extension }
    componentsExtension:
        class: AppBundle\Twig\ComponentsExtension
        public: false
        arguments: [  @translator, "%twig_components_extension%" ]
        tags:
            - { name: twig.extension }
    redirectorService:
        class: AppBundle\Service\Redirector
        arguments: [ @security.context, @router, @session, @util ]
    kernel.listener.login_listener:
        class: AppBundle\EventListener\LoginEventListener
        arguments: [ @event_dispatcher, @redirectorService ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    kernel.listener.session_listener:
        class: AppBundle\EventListener\SessionListener
        arguments: [ @router , {idleTimeout: %session_expire_seconds%}]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    logout_listener:
      class:   AppBundle\EventListener\LogoutListener
      arguments:  [@security.context, @router, @auditLogger]
    response_nocache_listener:
       class:   AppBundle\EventListener\ResponseNoCacheListener
       tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    form.reportSubmit: 
        class: AppBundle\Form\ReportSubmitType
        arguments:  [@translator]
    reportSubmitter:
        class: AppBundle\Service\ReportSubmitter
        arguments: [@service_container, @form.reportSubmit]
    auditLogger:
        class: AppBundle\Service\AuditLogger
        arguments: [@apiclient, @security.context, @service_container]
    app.form.type.report.assetTitle:
        class: AppBundle\Form\AssetTypeTitle
        arguments: [%asset_dropdown%, @translator, "report-assets", "other_assets"]
        tags:
            - { name: form.type, alias: asset_title }
    app.form.type.feedback:
        class: AppBundle\Form\FeedbackType
        calls:
            - [ setTranslator, [@translator] ]
        tags:
            - { name: form.type, alias: feedback }
    app.form.type.feedbackReport:
        class: AppBundle\Form\FeedbackReportType
        calls:
            - [ setTranslator, [@translator] ]
        tags:
            - { name: form.type, alias: feedback_report }