imports:
    - { resource: endpoints.yml }
    
services:
    apiclient:
        class:  AppBundle\Service\ApiClient
        arguments: [ @jms_serializer, {format: "json", base_url: "%api_base_url%", endpoints: "%api_endpoints%", debug: "%kernel.debug%"} ]
    deputyprovider:
        class:  AppBundle\UserProvider\DeputyProvider
        arguments: [ @apiclient, @jms_serializer ]
    formFieldsExtension:
        class: AppBundle\Twig\FormFieldsExtension
        public: false
        arguments: [ @translator ]
        tags:
            - { name: twig.extension }
       
    mailSender:
        class: AppBundle\Service\MailSender
        arguments: [ @apiclient, @translator, @router ]
        calls:
            - [setFrom, ["admin@digideps.service.dsd.io", "Digital deputyship service"]]