services:
    sendgrid:
      class: SendGrid
      arguments: [ "%sendgrid_username%", "%sendgrid_password%", {host: "api.sendgrid.com",} ]
        
    # pass it into Swift_Mailer to always write email into disk rather than sending them
    mailer.transport.fileWriter:
        class: AppBundle\Mailer\Transport\FileWriter
        arguments: [ "/tmp/dd_mail_mock" ]
        
    mailer.transport.secureSmtp:
        class: Swift_SmtpTransport
        arguments: [ "%smtp_hostname%", "%smtp_port%" ]
    
    mailer.transport.sendgrid:
        class: AppBundle\Mailer\Transport\SendGridTransport
        arguments: [ @sendgrid, "/tmp/dd_sendgrid_current_attachment.tmp"]
    userprovider:
        class: AppBundle\UserProvider\UserProvider
        arguments: [@doctrine.orm.entity_manager]
    granttype.apikey:
        class: AppBundle\OAuth\ApiKeyGrantExtension
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: fos_oauth_server.grant_extension, uri: http://digideps.local }
    user.query.filter:
        class: AppBundle\Service\UserQueryFilter
    app.doctrine.filter.configurator:
        class: AppBundle\Filter\Configurator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@fos_oauth_server.access_token_manager.default"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
