services:
  #Note: @s3_client is defined in config_dev  (using fakeS3) AND config_prod (using IAM credentials)
  s3_storage:
    class:  AppBundle\Service\File\Storage\S3Storage
    arguments: [ "@s3_client", "%s3_bucket_name%" ]
  file_checker_pdf:
    class: AppBundle\Service\File\Checker\PdfChecker
  file_checker_clam_av:
    class: AppBundle\Service\File\Checker\ClamAVChecker
  file_uploader:
    class: AppBundle\Service\File\FileUploader
    arguments: [ "@s3_storage", "@rest_client", "@logger" ]
    calls:
#      - [ addFileChecker, [ "@file_checker_pdf"]]
#      - [ addFileChecker, [ "@file_checker_clam_av"]]
