services:
    sendgrid:
      class: SendGrid
      arguments: [ "mojdsd-digideps-staging", "DobEjSuej", {host: "api.sendgrid.com"} ]
        
    mailer.transport.fileWriter:
        class: AppBundle\Mailer\Transport\FileWriter
        arguments: [ "/tmp/dd_mail_mock" ]
        
    mailer.transport.sendgrid:
        class: AppBundle\Mailer\Transport\SendGridTransport
        arguments: [ @sendgrid ]
    
    mailer.service:
        class: AppBundle\Mailer\MailerService
        arguments: ["%mailer_transport%", {sendgrid: @mailer.transport.sendgrid, file: @mailer.transport.fileWriter} ]
        
#    mailer.factory:
#        class: AppBundle\Mailer\MailerFactory
#        arguments: [ @mailer.service, @translator ]
#        calls:
#            - [setFrom, ["admin@digideps.service.dsd.io", "Digital deputyship service"]]
                
