services:
  s3_client:
    class: Aws\S3\S3Client
    arguments:
      -
        version: 'latest'
        region: 'eu-west-2'
        # only needed for fake S3
        endpoint: 'http://fakes3:4569'
        validate: false
        # credentials only needed for S3
        credentials:
          key: 'YOUR_ACCESS_KEY_ID'
          secret: 'YOUR_SECRET_ACCESS_KEY'
  s3_storage:
    class:  AppBundle\Service\File\Storage\S3Storage
    arguments: [ "@s3_client", "bucketName" ]
  file_checker_pdf:
    class: AppBundle\Service\File\Checker\PdfChecker
  file_checker_clam_av:
    class: AppBundle\Service\File\Checker\ClamAVChecker
  file_uploader:
    class: AppBundle\Service\File\FileUploader
    arguments: [ "@s3_storage", "@rest_client", "@logger" ]
    calls:
#      - [ addFileChecker, [ "@file_checker_pdf"]]
#      - [ addFileChecker, [ "@file_checker_clam_av"]]
