parameters:
  twig_components_extension:
    progress_bars:
      registration: [1,2,3,4]
      registration_admin: [1,2]
    tabs:
      report-paa: 
        tab-overview:
          path: "report_overview"
        tab-contacts:
          path: "contacts"
        tab-decisions:
          path: "decisions"
        tab-accounts:
          path: "accounts"
        tab-assets:
          path: "assets"
      report-pw:
          tab-overview:
              path: "report_overview"
          tab-contacts:
              path: "contacts"
          tab-decisions:
              path: "decisions"