version: 2.1

workflows:
  pull_request:
    jobs:
      - approve:
          name: approve test
          type: approval
          filters: { branches: { ignore: [ master ] } }

      - build:
          name: build pr
          requires: [ approve test ]
          semver_stage: --stage dev
          filters: { branches: { ignore: [ master ] } }

      - plan:
          requires: [ approve test ]
          filters: { branches: { ignore: [ master ] } }

      - slack/approval-notification:
          message: Version ${CIRCLE_TAG} is ready for release

  master:
    jobs:
      - build:
          name: build master
          filters: { branches: { only: [ master ] } }

      - apply:
          name: apply shared-development
          requires: [ build master ]
          filters: { branches: { only: [ master ] } }
          tf_tier: shared
          tf_workspace: development

      - apply:
          name: apply master
          requires: [ apply shared-development ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: master

      - stabilize:
          name: stabilize master
          requires: [ apply master ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: master

      - test:
          name: test master
          requires: [ stabilize master ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: master

      - apply:
          name: apply training
          requires: [ test master ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: training

      - stabilize:
          name: stabilize training
          requires: [ apply training ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: training

      - apply:
          name: apply shared-production
          requires: [ test master ]
          filters: { branches: { only: [ master ] } }
          tf_tier: shared
          tf_workspace: production

      - apply:
          name: apply preproduction
          requires: [ apply shared-production ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: preprod

      - stabilize:
          name: stabilize preproduction
          requires: [ apply preproduction ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: preprod

      - approve:
          name: approve release to production
          type: approval
          requires: [ stabilize preproduction ]
          filters: { branches: { only: [ master ] } }

      - apply:
          name: apply production
          requires: [ approve release to production ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: production02

      - stabilize:
          name: stabilize production
          requires: [ apply production ]
          filters: { branches: { only: [ master ] } }
          tf_workspace: production02

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  slack: circleci/slack@3.3.0

jobs:
  plan:
    docker:
      - image: hashicorp/terraform:full
    environment:
      TF_CLI_ARGS_plan: -input=false -lock=false
      TF_CLI_ARGS_init: -input=false -upgrade=true -reconfigure
    steps:
      - checkout
      - run:
          name: terraform lint
          command: terraform fmt -diff -check -recursive
      - run:
          name: init shared
          command: terraform init shared
      - run:
          name: plan shared
          environment:
            TF_WORKSPACE: development
          command: terraform plan -var-file=shared/terraform.tfvars.json shared
      - run:
          name: init environment
          command: terraform init environment
      - run:
          name: plan environment
          environment:
            TF_WORKSPACE: master
            TF_VAR_OPG_DOCKER_TAG: dummy_value
          command: terraform plan -var-file=environment/terraform.tfvars.json environment
  apply:
    docker:
      - image: hashicorp/terraform:full
    parameters:
      tf_workspace:
        description: terraform workspace
        type: string
      tf_tier:
        description: tier to apply - shared or environment
        default: environment
        type: string
    environment:
      TF_CLI_ARGS_apply: -input=false -auto-approve
      TF_CLI_ARGS_init: -input=false -upgrade=true -reconfigure
      TF_TIER: << parameters.tf_tier >>
      TF_WORKSPACE: << parameters.tf_workspace >>
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run:
          name: Get version
          command: cat VERSION.sh >> $BASH_ENV
      - run:
          name: Show version
          command: echo ${VERSION}
      - run:
          name: Initialize
          command: terraform init ${TF_TIER}
      - run:
          name: Apply
          command: TF_VAR_OPG_DOCKER_TAG=${VERSION} terraform apply -var-file=${TF_TIER}/terraform.tfvars.json ${TF_TIER}
  test:
    docker:
      - image: circleci/ruby
    parameters:
      tf_workspace:
        description: terraform workspace
        type: string
    environment:
      TF_WORKSPACE: << parameters.tf_workspace >>
      TF_VAR_default_role: digideps-ci
    working_directory: ~/project/environment
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Reset database
          command: ruby deployer/run_task.rb test-${TF_WORKSPACE} reset-database-${TF_WORKSPACE}
      - run:
          name: Test API
          command: ruby deployer/run_task.rb test-${TF_WORKSPACE} test-api-${TF_WORKSPACE}
      - run:
          name: Test Client
          command: ruby deployer/run_task.rb test-${TF_WORKSPACE} test-front-${TF_WORKSPACE}

  stabilize:
    docker:
      - image: circleci/ruby
    parameters:
      tf_workspace:
        description: terraform workspace
        type: string
    environment:
      TF_WORKSPACE: << parameters.tf_workspace >>
      TF_VAR_default_role: digideps-ci
    working_directory: ~/project/environment
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Check deployment
          command: ruby deployer/check_deployment.rb scan-${TF_WORKSPACE} front-${TF_WORKSPACE} admin-${TF_WORKSPACE} wkhtmltopdf-${TF_WORKSPACE}

  build:
    docker:
      - image: circleci/python:2.7
    parameters:
      semver_stage:
        description: semver stage suffix
        default: ""
        type: string
    environment:
      AWS_REGION: eu-west-1
      AWS_CONFIG_FILE: ~/project/aws_config
      AWS_REGISTRY: 311462405659.dkr.ecr.eu-west-1.amazonaws.com
    steps:
      - setup_remote_docker
      - aws-cli/install
      - add_ssh_keys:
          fingerprints:
            - 6f:4b:55:76:0e:cd:27:7d:ad:c3:28:38:53:69:5c:32
      - checkout
      - run:
          name: Install semvertag
          command: sudo pip install https://github.com/ministryofjustice/semvertag/archive/master.zip
      - run:
          name: Set next version
          command: echo "export VERSION=$(semvertag bump patch << parameters.semver_stage >>)" >> VERSION.sh
      - persist_to_workspace:
          root: .
          paths:
            - VERSION.sh
      - run:
          name: Get version
          command: cat VERSION.sh >> $BASH_ENV
      - run:
          name: Show version
          command: echo ${VERSION}
      - run:
          name: Tag git
          command: git tag ${VERSION}
      - run:
          name: Push git tags
          command: git push --tags
      - run:
          name: Docker login
          command: eval $(aws ecr get-login --region $AWS_REGION --no-include-email --profile digideps-ci)
      - run:
          name: Build api image
          command: docker build -t ${AWS_REGISTRY}/digideps/api:${VERSION} api
      - run:
          name: Build client image
          command: docker build -t ${AWS_REGISTRY}/digideps/client:${VERSION} client
      - run:
          name: Push api image
          command: docker push ${AWS_REGISTRY}/digideps/api:${VERSION}
      - run:
          name: Push client image
          command: docker push ${AWS_REGISTRY}/digideps/client:${VERSION}
