services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Predis\ClientInterface: '@snc_redis.default'

    AppBundle\:
        resource: "../../../src/*"
        exclude: '../../../src/{Entity}'

    AppBundle\Controller\:
        resource: "../../../src/Controller"
        tags: [controller.service_arguments]
