parameters:
  bad_pdf_keywords:
    - 'AcroForm'
    - 'JavaScript'
    - 'Launch'
    - 'RichMedia'
    - 'XFA'

services:
  Aws\S3\S3Client:
    arguments: ["%s3_client_params%"]

  s3_client:
    alias: Aws\S3\S3Client

  AppBundle\Service\File\Storage\S3Storage:
    arguments: [ "@s3_client", "%s3_bucket_name%", "@logger" ]

  s3_storage:
    alias: AppBundle\Service\File\Storage\S3Storage

  guzzle_file_scanner_client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: "%file_scanner_url%"
        verify: "%file_scanner_sslverify%"
        proxy: ""
        debug: false
        headers:
          Content-Type: multipart-form-data
        version: "1.1"

        timeout: 10
        allow_redirects: false

  AppBundle\Service\File\Verifier\MultiFileFormUploadVerifier:
    calls:
      - [ addVerifier, ['AppBundle\\Service\\File\\Verifier\\ConstraintVerifier'] ]
      - [ addVerifier, ['AppBundle\\Service\\File\\Verifier\\ScannerVerifier'] ]

  AppBundle\Service\File\Scanner\ClamFileScanner:
    arguments: [ "@guzzle_file_scanner_client", "@logger", "%bad_pdf_keywords%"]

  file_uploader:
    class: AppBundle\Service\File\FileUploader
    arguments: [ "@s3_storage", "@rest_client", "@logger" ]
