parameters:
  # To avoid undefined variable errors at build time during clear-cache, we can define default values for these env vars
  # At runtime Symfony will fetch the actual value from the environment
  env(AWS_REGION): 'dummy-build-time-value-overridden-at-runtime'
  env(AUDIT_LOG_GROUP_NAME): 'dummy-build-time-value-overridden-at-runtime'

services:
  Aws\CloudWatchLogs\CloudWatchLogsClient:
    class: Aws\CloudWatchLogs\CloudWatchLogsClient
    arguments:
      - region: '%env(AWS_REGION)%'
        version: "2014-03-28"

  AppBundle\Service\Audit\AuditLogHandler:
    class: AppBundle\Service\Audit\AuditLogHandler
    arguments:
      - '@Aws\CloudWatchLogs\CloudWatchLogsClient'
      - '%env(AUDIT_LOG_GROUP_NAME)%'
