services:
  Aws\CloudWatchLogs\CloudWatchLogsClient:
    class: Aws\CloudWatchLogs\CloudWatchLogsClient
    arguments:
      - region: '%env(AWS_REGION)%'
        version: "2014-03-28"

  AppBundle\Service\Audit\AuditLogHandler:
    class: AppBundle\Service\Audit\AuditLogHandler
    arguments:
      - '@Aws\CloudWatchLogs\CloudWatchLogsClient'
      - 'local-ddpb3349'
