[template]
prefix = "/frontend"
src = "parameters.yml.tmpl"
dest = "/app/app/config/parameters.yml"
keys = [
    "/role",
    "/session",
    "/ga",
    "/secret",
    "/api",
    "/fixtures",
    "/nonadmin"
 ]
