[template]
prefix = "/api"
src = "parameters.yml.tmpl"
dest = "/app/app/config/parameters.yml"
keys = [
    "/database",
    "/smtp",
    "/secret",
    "/security",
    "/email",
    "/email_settings",
    "/redis"
]
