# validation rule for each entity
AppBundle\Entity\User:
    properties:
        email:
            - NotBlank:
                message: "user.email.notBlank"
                groups: [ "admin_add_user" ]
            - Email:
                message: "user.email.invalid"
                checkMX: true
                checkHost: true
                groups: [ "admin_add_user" ]
        firstname:
            - NotBlank:
                message: "user.firstname.notBlank"
                groups: [ "admin_add_user", "user_details" ]
            - Length:
                min: 2
                max: 50
                minMessage: "user.firstname.minLength"
                maxMessage: "user.firstname.maxength"
                groups: [ "admin_add_user", "user_details" ]
        lastname:
            - NotBlank:
                message: "user.lastname.notBlank"
                groups: [ "admin_add_user", "user_details" ]
            - Length:
                min: 2
                max: 50
                minMessage: "user.lastname.minLength"
                maxMessage: "user.lastname.maxength"
                groups: [ "admin_add_user", "user_details" ]
        password:
            - NotBlank:
                message: "user.password.notBlank"
                groups: [ "user_set_password" ]
            - Length:
                min: 8
                max: 50
                minMessage: "user.password.minLength"
                maxMessage: "user.password.maxLength"
                groups: [ "user_set_password" ]
            - Regex:
                pattern: /[a-z]/   
                message: "user.password.noLowerCaseChars"
                groups: [ "user_set_password" ]
            - Regex:
                pattern: /[A-Z]/   
                message: "user.password.noUpperCaseChars"
                groups: [ "user_set_password" ]
            - Regex:
                pattern: /[0-9]/   
                message: "user.password.noNumber"
                groups: [ "user_set_password" ]
        roleId:
            - NotBlank:
                message: "user.role.notBlank"
                groups: [ "admin_add_user" ]
        address1:
            - NotBlank:
                message: "user.address1.notBlank"
                groups: [ "user_details" ]
        address2:
            - NotBlank:
                message: "user.address2.notBlank"
                groups: [ "user_details" ]
        address3:
            - NotBlank:
                message: "user.address3.notBlank"
                groups: [ "user_details" ]
        addressPostcode:
            - NotBlank:
                message: "user.addressPostcode.notBlank"
                groups: [ "user_details" ]
        addressCountry:
            - NotBlank:
                message: "user.addressCountry.notBlank"  
                groups: [ "user_details" ]     
        phoneHome:
            - NotBlank:
                message: "user.phoneHome.notBlank" 
                groups: [ "user_details" ]
        phoneWork:
#            - NotBlank:
#                message: "user.phoneWork.notBlank" 
#                groups: [ "user_details" ]
        phoneMobile:
#            - NotBlank:
#                message: "user.phoneMobile.notBlank" 
#                groups: [ "user_details" ]
                