AppBundle\Entity\User:
    properties:
        email:
            - NotBlank:
                message: "user.email.notBlank"
                groups: [ "admin_add_user" ]
            - Email:
                message: "user.email.invalid"
                checkMX: true
                checkHost: true
                groups: [ "admin_add_user" ]
        firstname:
            - NotBlank:
                message: "user.firstname.notBlank"
                groups: [ "admin_add_user" ]
            - Length:
                min: 2
                max: 50
                minMessage: "user.firstname.minLength"
                maxMessage: "user.firstname.maxength"
                groups: [ "admin_add_user" ]
        lastname:
            - NotBlank:
                message: "user.lastname.notBlank"
                groups: [ "admin_add_user" ]
            - Length:
                min: 2
                max: 50
                minMessage: "user.lastname.minLength"
                maxMessage: "user.lastname.maxength"
                groups: [ "admin_add_user" ]
        password:
            - NotBlank:
                message: "user.password.notBlank"
                groups: [ "user_set_password" ]
            - Length:
                min: 8
                max: 50
                minMessage: "user.password.minLength"
                maxMessage: "user.password.maxLength"
                groups: [ "user_set_password" ]
            - Regex:
                pattern: /[a-z]/   
                message: "user.password.noLowerCaseChars"
                groups: [ "user_set_password" ]
            - Regex:
                pattern: /[A-Z]/   
                message: "user.password.noUpperCaseChars"
                groups: [ "user_set_password" ]
            - Regex:
                pattern: /[0-9]/   
                message: "user.password.noNumber"
                groups: [ "user_set_password" ]
