AppBundle\Entity\User:
    properties:
        email:
            - NotBlank:
                message: "user.email.notBlank"
            - Email:
                message: "user.email.invalid"
                checkMX: true
                checkHost: true
        firstname:
            - NotBlank:
                message: "user.firstname.notBlank"
            - Length:
                min: 2
                max: 50
                minMessage: "user.firstname.minLength"
                maxMessage: "user.firstname.maxength"
        lastname:
            - NotBlank:
                message: "user.lastname.notBlank"
            - Length:
                min: 2
                max: 50
                minMessage: "user.lastname.minLength"
                maxMessage: "user.lastname.maxength"
        password:
            - Length:
                min: 8
                max: 50
                minMessage: "user.password.minLength"
                maxMessage: "user.password.maxLength"
            - Regex:
                pattern: /[a-z]/   
                message: "user.password.noLowerCaseChars"
            - Regex:
                pattern: /[A-Z]/   
                message: "user.password.noUpperCaseChars"
            - Regex:
                pattern: /[0-9]/   
                message: "user.password.noNumber"
