services:
  AppBundle\v2\Assembler\ClientAssembler:
    class: AppBundle\v2\Assembler\ClientAssembler
    arguments:
      - '@AppBundle\v2\Assembler\Report\ReportSummaryAssembler'
      - '@AppBundle\v2\Assembler\NdrAssembler'
      - '@PlainOrganisationAssembler'
      - '@PlainDeputyAssembler'

  ClientAssemblerFromReportEntity:
    class: AppBundle\v2\Assembler\ClientAssembler
    arguments:
      - '@AppBundle\v2\Assembler\Report\FullReportAssembler'
      - '@AppBundle\v2\Assembler\NdrAssembler'
      - '@PlainOrganisationAssembler'
      - '@PlainDeputyAssembler'

  PlainDeputyAssembler:
    class: AppBundle\v2\Assembler\DeputyAssembler

  PlainOrganisationAssembler:
    class: AppBundle\v2\Assembler\OrganisationAssembler
