services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\:
        resource: "../../../src/*"
        exclude: '../../../src/{Entity,Migrations,Tests,Kernel.php}'

    AppBundle\Controller\:
        resource: "../../../src/Controller"
        tags: [controller.service_arguments]
