services:

  AppBundle\Entity\Repository\UserRepository:
    class: AppBundle\Entity\User
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\User

  AppBundle\Entity\Repository\ReportRepository:
    class: AppBundle\Entity\Report\Report
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Report\Report
    calls:
      - [setSearchFilter, ["@AppBundle\\Service\\Search\\ClientSearchFilter"]]

  AppBundle\Entity\Repository\ClientRepository:
    class: AppBundle\Entity\Client
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Client
    calls:
      - [setSearchFilter, ["@AppBundle\\Service\\Search\\ClientSearchFilter"]]

  AppBundle\Entity\Repository\OrganisationRepository:
    class: AppBundle\Entity\Organisation
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Organisation
