services:
  AppBundle\Security\OrganisationVoter:
    class: AppBundle\Security\OrganisationVoter
    arguments: [ "@security.helper" ]
    tags:
        - { name: security.voter }

  AppBundle\Security\ClientVoter:
    class: AppBundle\Security\ClientVoter
    arguments: [ "@security.helper" ]
    tags:
        - { name: security.voter }
