services:
  AppBundle\v2\Transformer\NdrTransformer:
    class: AppBundle\v2\Transformer\NdrTransformer

  AppBundle\v2\Transformer\StatusTransformer:
    class: AppBundle\v2\Transformer\StatusTransformer

  AppBundle\v2\Transformer\ReportTransformer:
    class: AppBundle\v2\Transformer\ReportTransformer
    arguments:
      - '@AppBundle\v2\Transformer\StatusTransformer'

  AppBundle\v2\Transformer\ClientTransformer:
    class: AppBundle\v2\Transformer\ClientTransformer
    arguments:
      - '@AppBundle\v2\Transformer\ReportTransformer'
      - '@AppBundle\v2\Transformer\NdrTransformer'
      - '@PlainOrganisationTransformer'
      - '@PlainDeputyTransformer'

  AppBundle\v2\Transformer\DeputyTransformer:
    class: AppBundle\v2\Transformer\DeputyTransformer
    arguments:
      - '@AppBundle\v2\Transformer\ClientTransformer'

  PlainDeputyTransformer:
    class: AppBundle\v2\Transformer\DeputyTransformer

  AppBundle\v2\Transformer\OrganisationTransformer:
    class: AppBundle\v2\Transformer\OrganisationTransformer
    arguments:
      - '@AppBundle\v2\Transformer\DeputyTransformer'
      - '@AppBundle\v2\Transformer\ClientTransformer'

  PlainOrganisationTransformer:
    class: AppBundle\v2\Transformer\OrganisationTransformer

