imports:
    - { resource: config_prod.yml }

framework:
    test: ~

services:
    AppBundle\Service\Mailer\MailSender:
        class: AppBundle\Service\Mailer\MailSenderMock
        autowire: true

    Alphagov\Notifications\Client:
        alias: AppBundle\Service\Mailer\NotifyClientMock
