imports:
    - { resource: services/defaults.yml }
    - { resource: services/file_uploads.yml }
    - { resource: services/mappers.yml }
    - { resource: services/resolvers.yml }
    - { resource: services/transformers.yml }
    - { resource: services/twig.yml }
    - { resource: services_mail.yml }
    - { resource: services_forms.yml }
    - { resource: services_api.yml }
    - { resource: services_listeners.yml }
    - { resource: services_login.yml }

services:
    AppBundle\Service\Redirector:
        class: AppBundle\Service\Redirector
        arguments: [ "@security.token_storage", "@security.authorization_checker", "@router", "@session", "%env%" ]

    redirector_service:
        alias: AppBundle\Service\Redirector

    AppBundle\Service\WkHtmlToPdfGenerator:
        arguments: [ "%wkhtmltopdf_address%", 30]

    wkhtmltopdf:
        alias: AppBundle\Service\WkHtmlToPdfGenerator

    step_redirector:
      alias: AppBundle\Service\StepRedirector

    csv_generator_service:
      alias: AppBundle\Service\CsvGeneratorService

    # Disable autowiring
    AppBundle\Model\EmailAttachment: ~
    AppBundle\Service\DataImporter\CsvToArray: ~
    AppBundle\Service\NdrStatusService: ~

    guzzle_api_gateway_client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                timeout: 10
                allow_redirects: false

    AppBundle\Service\Client\Sirius\SiriusApiGatewayClient:
        class: AppBundle\Service\Client\Sirius\SiriusApiGatewayClient
        arguments:
            $httpClient: '@guzzle_api_gateway_client'
            $requestSigner: '@AppBundle\Service\AWS\RequestSigner'
            $baseUrl: '%env(SIRIUS_API_BASE_URI)%'

    AppBundle\Service\AWS\RequestSigner:
        class: AppBundle\Service\AWS\RequestSigner
