services:
    mailer.transport.smtp.default:
        class: Swift_SmtpTransport
        arguments: [ "%smtp_default_hostname%", "%smtp_default_port%" ]
        calls:
            - [ setEncryption, [ "tls"]]
            - [ setUsername, [ "%smtp_default_user%"]]
            - [ setPassword, [ "%smtp_default_password%"]]

    mailer.swift_mailers.default:
        class: Swift_Mailer
        arguments: [ "@mailer.transport.smtp.default" ]

    AppBundle\Service\Mailer\MailFactory:
        autowire: true
        arguments:
            $emailParams:
                from_email: '%from_email%'
                report_submit_to_address: '%report_submit_to_address%'
                feedback_send_to_address: '%feedback_send_to_address%'
                update_send_to_address: '%update_send_to_address%'
            $baseURLs:
                front: '%env(NONADMIN_HOST)%'
                admin: '%env(ADMIN_HOST)%'

    # mail sender accepting those the above-created swift mailer
    AppBundle\Service\Mailer\MailSender:
        autowire: true
        calls:
            - [ addSwiftMailer, [ 'default', '@mailer.swift_mailers.default'] ]

    Alphagov\Notifications\Client:
        class: Alphagov\Notifications\Client
        arguments:
            $config:
                httpClient: '@Http\Adapter\Guzzle6\Client'
                apiKey: '%env(NOTIFY_API_KEY)%'

    Http\Adapter\Guzzle6\Client:
        class: Http\Adapter\Guzzle6\Client
