services:
    GuzzleHttp\Client:
        arguments:
          $config:
            base_uri: "%api_base_url%"
            verify: false
            # force HTTP 1.0 in order to disable HTTP1.1-chunking corrupting JSON decoding
            version: "1.0"
            headers:
                Content-Type: application/json
            timeout: 20
            allow_redirects: false

    AppBundle\Service\Client\RestClient:
        arguments:
            - "@service_container"
            - "@GuzzleHttp\\Client"
            - "@AppBundle\\Service\\Client\\TokenStorage\\RedisStorage"
            - "@jms_serializer"
            - "@logger"
            - "%api_client_secret%"

    rest_client:
        alias: AppBundle\Service\Client\RestClient
