services:
  s3_client:
    class: Aws\S3\S3Client
    arguments: ["%s3_client_params%"]

  s3_storage:
    class:  AppBundle\Service\File\Storage\S3Storage
    arguments: [ "@s3_client", "%s3_bucket_name%", "@logger" ]

  guzzle_file_scanner_client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: "%file_scanner_url%"
        verify: "%file_scanner_sslverify%"
        proxy: ""
        debug: false
        headers:
          Content-Type: multipart-form-data
        version: "1.1"

        timeout: 10
        allow_redirects: false

  multi_file_form_upload_handler:
    class: AppBundle\Service\File\MutliFileFormUploadHandler
    arguments: ['@upload_verifier']

  upload_verifier:
    class: AppBundle\Service\File\Verifier\CompositeVerifier
    calls:
      - [ addVerifier, ['@constraint_verifier'] ]
      - [ addVerifier, ['@scanner_verifier'] ]

  constraint_verifier:
    class: AppBundle\Service\File\Verifier\ConstraintVerifier
    arguments: ['@validator']

  scanner_verifier:
    class: AppBundle\Service\File\Verifier\ScannerVerifier
    arguments: ['@file_scanner', '@translator', '@logger']

  file_scanner:
    class: AppBundle\Service\File\Scanner\FileScanner
    arguments: [ "@guzzle_file_scanner_client", "@logger" , "@scanner_endpoint_resolver" ]

  scanner_endpoint_resolver:
    class: AppBundle\Service\File\Scanner\ScannerEndpointResolver

  file_uploader:
    class: AppBundle\Service\File\FileUploader
    arguments: [ "@s3_storage", "@rest_client", "@logger" ]
