services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Service\Mailer\MailFactory:
        arguments:
            $emailParams: %email_params%
            $baseURLs:
                front: '%env(NONADMIN_HOST)%'
                admin: '%env(ADMIN_HOST)%'

    # mail sender accepting those the above-created swift mailer
    AppBundle\Service\Mailer\MailSender:
        class: AppBundle\Service\Mailer\MailSender

    Alphagov\Notifications\Client:
        class: Alphagov\Notifications\Client
        arguments:
            $config:
                httpClient: '@Http\Adapter\Guzzle6\Client'
                apiKey: '%env(NOTIFY_API_KEY)%'

    Http\Adapter\Guzzle6\Client:
        class: Http\Adapter\Guzzle6\Client
